### ISSUE TITLE
Vite compatibility: `Error: Unexpected usage`…`EditorSimpleWorker.loadForeignModule`

### ISSUE THREAD

**Issue by JulianCataldo** [remcohaszing/monaco-unified#1]
Hello!

I'm trying to make it work with Vite, but I'm stumbling upon this so far:

```
editorSimpleWorker.js:463 Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:463:31)
    at webWorker.js:38:30
    at async Object.provideMarkerData (languageFeatures.js:13:28)
    at async doValidate (index.js:21:25)
```

I'll make a repro. ASAP.

**Comment by JulianCataldo** [comment]
This is the repro:

https://stackblitz.com/edit/vitejs-vite-p7mkqm

Same error with Firefox and Chromium:

<img width="472" alt="Screenshot 2023-01-31 at 20 59 29" src="https://user-images.githubusercontent.com/603498/215869373-4d91b055-ead9-45e4-9c44-fa549c98c140.png">


While commented out, Monaco YAML installation is working in this reproduction.
I tried to kind of "port" the Vite tricks from it to Monaco unified, but not sure on how to achieve that, as they are structured differently regarding worker import / ignition.

**Comment by remcohaszing** [comment]
What your screenshot shows is the generic Monaco editor error meaning it failed to load the worker. There’s an actual error too, saying something about `document` being undefined. This is because `document` doesn’t exist in web workers. I’m unable to screenshot this, because Stackblitz is being flaky.

Your options are to:
1. Alias `decode-named-character-reference` to the web worker compatible export, like in https://github.com/remcohaszing/monaco-unified/blob/main/examples/demo/webpack.config.js#L18-L20
2. Make vite use the `worker` condition. This means it will apply to all imports though. I haven’t really seen negative effects of this myself.
   ```js
   import { defineConfig } from 'vite';

   export default defineConfig({
     resolve: {
       conditions: ['worker']
     }
   })
   ```
3. Upvote https://github.com/vitejs/vite/issues/7439

Perhaps this project should define an FAQ, like https://github.com/remcohaszing/monaco-yaml#faq. I think this issue you can would fit in there.

**Comment by JulianCataldo** [comment]
It worked immediately with the Option #2 three-liner, great!
Will keep what you said in mind though, and report if anything weird happens.
